theme: jekyll-theme-architect
Name: "Reddy’s Home"
navbar: 
  title: Home
  left:
  - text: R Learning
    href: content.html
    
  - text: 耕读社
    href: 耕读社.html
output:
  html_document:
    theme: flatly
